package com.revature.drivers;

import java.util.List;

import com.revature.models.Customer;
import com.revature.models.Videogame;
import com.revature.repositories.CustomerDao;
import com.revature.repositories.CustomerPostgres;
import com.revature.repositories.VideogameDao;
import com.revature.repositories.VideogamePostgres;

public class JbdcDriver {
	
	public static void main(String[] args) {
	
		//Customers
		CustomerDao cd = new CustomerPostgres();

		List<Customer> cus = cd.getCustomers();
		for (Customer c : cus) {
			System.out.println(c);
		}
		
		System.out.println("Get customer by id 6:" + cd.getCustomerById(6));
		
		Customer newCus = new Customer("Brayden", "BraydenW", "1234", 56781234);
		
		
		int idNewCus = cd.addCustomer(newCus);
		System.out.println("Generated id was: " + idNewCus);
		
		
		System.out.println("Deleted columns: " + cd.deleteCustomer(idNewCus));
		
		
		Customer newCus2 = new Customer(6, "Hannah", "HannahW", "5678", 67892345);

		System.out.println("Update successfully: " + cd.updateCustomer(newCus2));
		
		
		
		//Employees
//		EmployeeDao ed = new EmployeePostgres();
//
//		List<Employee> emps = ed.getEmployees();
//		for (Employee e : emps) {
//			System.out.println(e);
//		}
//		
//		System.out.println("Get employeeById 4:" + ed.getEmployeeById(4));
//		
//		Employee newEmp = new Employee("TestName", "TestUsername", "TestPass", "TestRole", new Employee(4));
//		
//		//saving the id generated by the database
//		int idNewEmp = ed.addEmployee(newEmp);
//		System.out.println("Generated id was: " + idNewEmp);
//		
//		//delete employee at id idNewEmp and return the number of rows changed
//		System.out.println("Deleted columns: " + ed.deleteEmployee(idNewEmp));
//		
//		
//		Employee newEmp2 = new Employee(6, "TestName", "TestUsername", "TestPass", "TestRole", new Employee(6));
//
//		System.out.println("Update successfully: " + ed.updateEmployee(newEmp2));
		
		//Videogames
		VideogameDao vd = new VideogamePostgres();

		List<Videogame> vg = vd.getVideogames();
		for (Videogame v : vg) {
			System.out.println(v);
		}
				
		System.out.println("Get videogame by id 4:" + vd.getVideogameById(4));
				
		Videogame newVG = new Videogame("Super Mario Odyssey", "Nintendo", "Platformer", 59.99, 24);
				
				
		int idNewVG = vd.addVideogame(newVG);
		System.out.println("Generated id was: " + idNewVG);
				
				
		System.out.println("Deleted columns: " + vd.deleteVideogame(idNewVG));
				
				
		Videogame newVG2 = new Videogame(6, "Luigi's Mansion 3", "Nintendo", "Platformer", 59.99, 21);

		System.out.println("Update successfully: " +vd.updateVideogame(newVG2));
	}

}
